Checkstyle error fix - HelloWorldTest.java #5
jody/helloCS3250 pull request #9
Opened 2020-10-09 21:51 UTC by GOKU900

Removed unused import static org.junit.jupiter.api.Assertions.assertTrue; from HelloWorldTest.java

2020-10-09 23:04 UTC, jody approved these changes

2020-10-09 23:09 UTC, jody requested changes
Please update the version number (increment the least-significant digit) and squash the commits.

2020-10-10 20:36 UTC, GOKU900 commented
Could you explain what "force-pushed" means and why it appears after I squashed my commits? From what I read on the internet its not good. Not sure where I went wrong. I used the following commands:

$ git pull upstream main                               (32)
$ git push -f origin main

2020-10-11 00:59 UTC, jody commented
> Could you explain what "force-pushed" means and why it appears after I squashed my commits? From what I read on the internet its not good. Not sure where I went wrong. I used the following commands:
> 
> $ git rebase -i master
> $ git push -f origin checkstylefix

The -f option is the same as --force.  This option disables some checks on the push, allowing you to update remote refs that aren't ancestors of the local refs.  You can read about the push command and the -f option by using: `git help push`.  In general, we want to preserve the commit history so we wouldn't use the -f option.  But when the change being made is _intended_ to _replace_ a commit, then the -f option is appropriate.  As part of the squash, you do want to replace already-made commits.  That is, you are intentionally changing the history of your branch in origin.

2020-10-11 05:06 UTC, merged